version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: kodanect-python-dev
    ports:
      - "8000:8000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      UPSTAGE_API_KEY: ${UPSTAGE_API_KEY}
    volumes:
      - .:/app
    networks:
      - kodanect-backend-springboot_kodanect-net

networks:
  kodanect-backend-springboot_kodanect-net:
    external: true